### ISSUE TITLE
Please provide a PDF version doc to download

### ISSUE THREAD

**Issue by jkryanchou** [solidity-docs/zh-chinese#240]
I have read from the ReadTheDocs, while there is no PDF version/choice to download, Could you provide a PDF version/choice to download?

**Comment by Skyge** [comment]
Hi, sorry for this, there is something wrong with the PDF version, have not solved it.

**Comment by jkryanchou** [comment]
@Skyge Got it. I have tried many times with different latex configuration. It didn't work either. I am so looking forward to the PDF version which is convenient for me to read in some Reader app in iOS

**Comment by r0qs** [comment]
Hi @jkryanchou,

Long story short, Sphinx doesn't support SVG by default, and the `pdf` builds were breaking the builds of the docs, thus we disabled it at that time. See https://github.com/sphinx-doc/sphinx/issues/1907 for details of the original issue.

We added the `sphinx.ext.imgconverter` extension in the `develop` branch of the Solidity repo a while ago (https://github.com/ethereum/solidity/pull/14096). But we forgot to re-enable the `pdf` builds in the read-the-docs settings. Now that read-the-docs is migrating to a new version of configuration files and requires that all builds use such configuration, just re-enabling the `pdf` in the read-the-docs settings will break the docs generation (as you can see here: https://readthedocs.org/projects/solidity-docs-chinese/builds/21822555/).

Everything should start to work again, including the `pdf` builds, as soon as we merge: https://github.com/solidity-docs/zh-chinese/pull/279.

**Comment by jkryanchou** [comment]
Looking forward the PDF version which could be portable to package it in my mobile phone or notebook.

**Comment by Skyge** [comment]
@jkryanchou Have solved this issue. Now, you can use the [latest documentation](https://docs.soliditylang.org/zh/latest/), it has a PDF version. **Notice The English reference version is and will remain the only officially supported version. so when in doubt, please always refer to the [English (original) documentation](https://docs.soliditylang.org/en/latest/).**

**Comment by r0qs** [comment]
> @jkryanchou Have solved this issue. Now, you can use the [latest documentation](https://docs.soliditylang.org/zh/latest/), it has a PDF version. **Notice The English reference version is and will remain the only officially supported version. so when in doubt, please always refer to the [English (original) documentation](https://docs.soliditylang.org/en/latest/).**

Exactly! Also, if needed, we can cherry-pick the commit, apply to the older versions and regenerate the documentation, so the PDF version would also be available for those.
